use Mix.Config

fetch_environment_variable! = fn key ->
  System.get_env(key, nil) || throw("Unable to get env variable '#{key}'")
end

database_username = fetch_environment_variable!.("DATABASE_USERNAME")
database_host = fetch_environment_variable!.("DATABASE_HOST")
database_port = fetch_environment_variable!.("DATABASE_PORT")
database_password = fetch_environment_variable!.("DATABASE_PASSWORD")
database_database = fetch_environment_variable!.("DATABASE_DATABASE")
port = fetch_environment_variable!.("PORT") |> :erlang.binary_to_integer()

# Configure your database
config :communication, Communication.Repo,
  username: database_username,
  password: database_password,
  database: database_database,
  hostname: database_host,
  port: database_port,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :communication, CommunicationWeb.Endpoint,
  http: [port: port],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :communication, CommunicationWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/communication_web/(live|views)/.*(ex)$",
      ~r"lib/communication_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
